### ISSUE TITLE
failed to fetch skin on first join

### ISSUE THREAD

**Issue by exsolvere** [Suiranoil/SkinRestorer#26]
[21:58:55] [ForkJoinPool.commonPool-worker-8/ERROR]: failed to fetch skin on first join
java.lang.IllegalStateException: not found
        at fabric.net.lionarius.skinrestorer.util.WebUtils.throwOnClientErrors(WebUtils.java:97) ~[skin-restorer-2.0.0+1.20.5.jar:?]
        at fabric.net.lionarius.skinrestorer.skin.provider.MojangSkinProvider.getUuid(MojangSkinProvider.java:73) ~[skin-restorer-2.0.0+1.20.5.jar:?]
        at fabric.net.lionarius.skinrestorer.skin.provider.MojangSkinProvider.getSkin(MojangSkinProvider.java:51) ~[skin-restorer-2.0.0+1.20.5.jar:?]
        at net.minecraft.class_3248.mdd6486d$skinrestorer$lambda$waitForSkin$0$1(class_3248.java:2057) ~[server-intermediary.jar:?]
        at java.base/java.util.Optional.map(Optional.java:260) ~[?:?]
        at net.minecraft.class_3248.mdd6486d$skinrestorer$lambda$waitForSkin$1$0(class_3248.java:2056) ~[server-intermediary.jar:?]
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) [?:?]
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) [?:?]
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) [?:?]
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312) [?:?]
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843) [?:?]
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808) [?:?]
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188) [?:?]

The newest update shows this only if a player connects using geyser and floodgate. I haven't seen any negative impact it has, but I'm worried it might mess something up. Is this fine?

**Comment by Suiranoil** [comment]
Its fine.

The mod tries to fetch skin for players who join for "the first time" (e.g. dont have any skin) based on their username. If there is some error while doing so it just prints it to the console. In your case it could not find mojang account with player's username.

You can ignore it or disable this behaviour in config https://github.com/Suiranoil/SkinRestorer/wiki/Config#fetchskinonfirstjoin

**Comment by Legendmanj** [comment]
> Its fine.
> 
> The mod tries to fetch skin for players who join for "the first time" (e.g. dont have any skin) based on their username. If there is some error while doing so it just prints it to the console. In your case it could not find mojang account with player's username.
> 
> You can ignore it or disable this behaviour in config https://github.com/Suiranoil/SkinRestorer/wiki/Config#fetchskinonfirstjoin

the error happens normally for me too, what would you recommend for a cracked server?
