### ISSUE TITLE
In skin menu, favorites page doesn't open

### ISSUE THREAD

**Issue by le0nlol** [Suiranoil/SkinRestorer#38]
Here are logs when I try to do it:

[19:15:26 WARN]: [SkinsRestorer] Async task for SkinsRestorer v15.4.4 generated an exception
java.util.NoSuchElementException: No value present
        at SkinsRestorer.jar/net.skinsrestorer.shadow.jvmdowngrader.xyz.wagyourtail.jvmdg.j10.stub.java_base.J_U_Optional.orElseThrow(J_U_Optional.java:16) ~[SkinsRestorer.jar:?]
        at SkinsRestorer.jar/net.skinsrestorer.shared.storage.GUIStorage$5.lambda$getGUISkins$0(GUIStorage.java:197) ~[SkinsRestorer.jar:?]
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1708) ~[?:?]
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575) ~[?:?]
        at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260) ~[?:?]
        at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616) ~[?:?]
        at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622) ~[?:?]
        at SkinsRestorer.jar/net.skinsrestorer.shadow.jvmdowngrader.xyz.wagyourtail.jvmdg.j16.stub.java_base.J_U_S_Stream.toList(J_U_S_Stream.java:40) ~[SkinsRestorer.jar:?]
        at SkinsRestorer.jar/net.skinsrestorer.shared.storage.GUIStorage$5.getGUISkins(GUIStorage.java:200) ~[SkinsRestorer.jar:?]
        at SkinsRestorer.jar/net.skinsrestorer.shared.gui.GUIUtils.getGUIPage(GUIUtils.java:70) ~[SkinsRestorer.jar:?]
        at SkinsRestorer.jar/net.skinsrestorer.shared.storage.GUIStorage.getGUIPage(GUIStorage.java:55) ~[SkinsRestorer.jar:?]
        at SkinsRestorer.jar/net.skinsrestorer.shared.listeners.GUIActionListener.handle(GUIActionListener.java:46) ~[SkinsRestorer.jar:?]
        at SkinsRestorer.jar/net.skinsrestorer.shared.gui.ActionDataCallback.lambda$handle$0(ActionDataCallback.java:42) ~[SkinsRestorer.jar:?]
        at SkinsRestorer.jar/net.skinsrestorer.bukkit.folia.FoliaSchedulerProvider.lambda$getCancellingTaskConsumer$0(FoliaSchedulerProvider.java:84) ~[SkinsRestorer.jar:?]
        at io.papermc.paper.threadedregions.scheduler.FoliaAsyncScheduler$AsyncScheduledTask.run(FoliaAsyncScheduler.java:217) ~[paper-1.21.jar:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

**Comment by Suiranoil** [comment]
You are having issue with [SkinsRestorer bukkit plugin](https://www.spigotmc.org/resources/skinsrestorer.2124/). You should use their discord server for support.
